//! The window state as it is before the backend has said anything.

use super::*;

impl LauncherUI {
    pub fn new(backend: BackendHandle) -> Self {
        // Ask right away; the answer comes once the ws connects.
        backend.send(MessageToBackend::RequestServerList);
        backend.send(MessageToBackend::RequestNews);
        Self {
            backend,
            page: Page::Login,
            profile_tab: ProfileTab::Overview,
            user: None,
            skin_image: None,
            skin_preview: None,
            skin_bytes: None,
            skin_url: None,
            skin_yaw: 0.0,
            skin_sway: 0.0,
            skin_loading: false,
            skin_uploading: false,
            skin_before_upload: None,
            skin_dragging: false,
            skin_drag_x: 0.0,
            skin_anim_running: false,
            skin_decoded: None,
            window_active: true,
            cape_bytes: None,
            cape_url: None,
            cape_loading: false,
            capes: Vec::new(),
            cape_images: std::collections::HashMap::new(),
            preset_images: std::collections::HashMap::new(),
            custom_presets: Vec::new(),
            cape_selector_open: false,
            build_picker_open: false,
            avatar_image: None,
            avatar_loading: false,
            perf: Default::default(),
            locale: i18n::Locale::default(),
            online: false,
            connection_lost: false,
            logging_in: false,
            sidebar_collapsed: false,
            mod_catalog_hits: Vec::new(),
            mod_catalog_selected: None,
            mod_catalog_provider: "modrinth".to_string(),
            mod_catalog_query: String::new(),
            mod_catalog_focus: None,
            mod_project: None,
            mod_detail_gallery: false,
            mod_catalog_total: 0,
            mod_catalog_offset: 0,
            mod_catalog_limit: 20,
            mod_catalog_error: None,
            renaming_preset: None,
            rename_focus: None,
            startup_checking: true,
            login_error: None,
            login_modal: None,
            login_mode_key: false,
            login_key_input: String::new(),
            login_key_focus: None,
            servers: Vec::new(),
            selected_build: std::collections::HashMap::new(),
            news: Vec::new(),
            sync: HashMap::new(),
            build_state: HashMap::new(),
            logs: HashMap::new(),
            optional_mods: HashMap::new(),
            installed_file_keys: HashMap::new(),
            installed_keys: HashMap::new(),
            allow_mod_suggestions: HashMap::new(),
            allow_personal_content: HashMap::new(),
            suggested_mods: HashSet::new(),
            background_images: HashMap::new(),
            news_images: HashMap::new(),
            news_excerpts: HashMap::new(),
            news_images_loading: HashSet::new(),
            server_icons: HashMap::new(),
            optional_mod_icons: HashMap::new(),
            background_image_urls: HashMap::new(),
            server_icon_urls: HashMap::new(),
            background_loading: HashSet::new(),
            icons_loading: HashSet::new(),
            optional_mod_icons_loading: HashSet::new(),
            optional_mod_icons_failed: HashSet::new(),
            image_failed: HashSet::new(),
            update_available: None,
            impersonate_prompt: None,
            log_request_prompt: None,
            log_request_preview_open: false,
            remote_action_prompt: None,
            impersonating_as: None,
            updating: false,
            update_modal: None,
            toasts: Vec::new(),
            next_toast_id: 0,
            config: UiConfig::default(),
            server_settings: HashMap::new(),
            server_recommendations: HashMap::new(),
            console_window: None,
            main_window: None,
            close_prompt: false,
            armed_action: None,

            notifications: Vec::new(),
            notifications_total: 0,
            unread: 0,
            notifications_open: false,
            notifications_loading: false,
            notifications_unread_only: false,

            personal_content: HashMap::new(),
            content_versions: HashMap::new(),
            content_picker: None,
            content_versions_all: false,
            content_kind: schema::personal::ContentKind::Mod,
            content_mode: ContentMode::default(),
            content_busy: false,
            content_error: None,
            content_show_installed: false,
            content_sort: "relevance".to_string(),
            content_requested_for: None,
            content_searching: false,

            java_options: HashMap::new(),
            java_selected: HashMap::new(),
            java_default: HashMap::new(),
            java_busy: false,
            java_picker_open: false,
            jvm_flags_open: false,
            jvm_flags_draft: String::new(),
            jvm_flags_focus: None,

            account_tab: AccountTab::default(),
            account_requested: HashSet::new(),
            account_loaded: HashSet::new(),
            dm_loaded: false,
            news_loaded: false,
            ui_state: crate::ui_state::load(),
            last_server_restored: false,
            punishments: Vec::new(),
            rules: Vec::new(),
            rules_query: String::new(),
            rules_focus: None,
            tickets: Vec::new(),
            ticket_open: None,
            dm_threads: Vec::new(),
            dm_requested: false,
            dm_open: None,
            dm_scroll: gpui::ScrollHandle::new(),
            ticket_scroll: gpui::ScrollHandle::new(),
            compose: String::new(),
            compose_focus: None,
        }
    }
}
