modLoader = "javafml"
loaderVersion = "[20,)"
license = "MIT"

[[mixins]]
config = "noro-agent.mixins.json"

[[mods]]
modId = "noro_agent"
version = "${version}"
displayName = "Noro Agent"
authors = "noro"
description = '''Projects master roles, access and online count onto this server.'''

[[dependencies.noro_agent]]
modId = "neoforge"
type = "required"
versionRange = "[20.2,)"
ordering = "NONE"
side = "SERVER"
