[package]
name = "noro_launcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "noro-launcher"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["rt", "net", "macros"] }
reqwest = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
anyhow = { workspace = true }
dirs = { workspace = true }

[build-dependencies]
winres = "0.1"
